

namespace ZennoPosterYandexRegistrationSmsServiceSmsHubOrg
{
    class ApiResponceJsonToCSharp
    {
        public class CountFreeNumber
        {
            public string vk_0 { get; set; }
            public string ok_0 { get; set; }
            public string wa_0 { get; set; }
            public string vi_0 { get; set; }
            public string tg_0 { get; set; }
            public string wb_0 { get; set; }
            public string go_0 { get; set; }
            public string av_0 { get; set; }
            public string fb_0 { get; set; }
            public string tw_0 { get; set; }
            public string ub_0 { get; set; }
            public string qw_0 { get; set; }
            public string gt_0 { get; set; }
            public string sn_0 { get; set; }
            public string ig_0 { get; set; }
            public string ss_0 { get; set; }
            public string ym_0 { get; set; }
            public string ma_0 { get; set; }
            public string mm_0 { get; set; }
            public string uk_0 { get; set; }
            public string me_0 { get; set; }
            public string mb_0 { get; set; }
            public string we_0 { get; set; }
            public string bd_0 { get; set; }
            public string kp_0 { get; set; }
            public string dt_0 { get; set; }
            public string ya_0 { get; set; }
            public string mt_0 { get; set; }
            public string oi_0 { get; set; }
            public string fd_0 { get; set; }
            public string zz_0 { get; set; }
            public string kt_0 { get; set; }
            public string pm_0 { get; set; }
            public string tn_0 { get; set; }
            public string qq_0 { get; set; }
            public string mg_0 { get; set; }
            public string pf_0 { get; set; }
            public string yl_0 { get; set; }
            public string kl_0 { get; set; }
            public string po_0 { get; set; }
            public string nv_0 { get; set; }
            public string nf_0 { get; set; }
            public string iq_0 { get; set; }
            public string ob_0 { get; set; }
            public string kb_0 { get; set; }
            public string im_0 { get; set; }
            public string mc_0 { get; set; }
            public string ds_0 { get; set; }
            public string vv_0 { get; set; }
            public string ji_0 { get; set; }
            public string lf_0 { get; set; }
            public string hu_0 { get; set; }
            public string wg_0 { get; set; }
            public string rz_0 { get; set; }
            public string vf_0 { get; set; }
            public string ny_0 { get; set; }
            public string rr_0 { get; set; }
            public string fe_0 { get; set; }
            public string la_0 { get; set; }
            public string zh_0 { get; set; }
            public string gp_0 { get; set; }
            public string am_0 { get; set; }
            public string ly_0 { get; set; }
            public string tc_0 { get; set; }
            public string dp_0 { get; set; }
            public string pg_0 { get; set; }
            public string yf_0 { get; set; }
            public string op_0 { get; set; }
            public string fx_0 { get; set; }
            public string qr_0 { get; set; }
            public string yk_0 { get; set; }
            public string ls_0 { get; set; }
            public string bl_0 { get; set; }
            public string mu_0 { get; set; }
            public string fu_0 { get; set; }
            public string bf_0 { get; set; }
            public string sg_0 { get; set; }
            public string uu_0 { get; set; }
            public string ua_0 { get; set; }
            public string ab_0 { get; set; }
            public string iv_0 { get; set; }
            public string zy_0 { get; set; }
            public string gd_0 { get; set; }
            public string fy_0 { get; set; }
            public string ce_0 { get; set; }
            public string tl_0 { get; set; }
            public string hm_0 { get; set; }
            public string tx_0 { get; set; }
            public string ka_0 { get; set; }
            public string pl_0 { get; set; }
            public string ip_0 { get; set; }
            public string cm_0 { get; set; }
            public string hw_0 { get; set; }
            public string de_0 { get; set; }
            public string jc_0 { get; set; }
            public string rl_0 { get; set; }
            public string df_0 { get; set; }
            public string ui_0 { get; set; }
            public string up_0 { get; set; }
            public string nz_0 { get; set; }
            public string kf_0 { get; set; }
            public string ri_0 { get; set; }
            public string cc_0 { get; set; }
            public string lr_0 { get; set; }
            public string za_0 { get; set; }
            public string da_0 { get; set; }
            public string ug_0 { get; set; }
            public string sq_0 { get; set; }
            public string zr_0 { get; set; }
            public string xv_0 { get; set; }
            public string cx_0 { get; set; }
            public string cw_0 { get; set; }
            public string li_0 { get; set; }
            public string dz_0 { get; set; }
            public string xz_0 { get; set; }
            public string rd_0 { get; set; }
            public string qb_0 { get; set; }
            public string hz_0 { get; set; }
            public string gl_0 { get; set; }
            public string zk_0 { get; set; }
            public string ia_0 { get; set; }
            public string xl_0 { get; set; }
            public string yi_0 { get; set; }
            public string ew_0 { get; set; }
            public string ae_0 { get; set; }
            public string gb_0 { get; set; }
            public string cy_0 { get; set; }
            public string qm_0 { get; set; }
            public string dh_0 { get; set; }
            public string yb_0 { get; set; }
            public string qe_0 { get; set; }
            public string yw_0 { get; set; }
            public string uz_0 { get; set; }
            public string gx_0 { get; set; }
            public string re_0 { get; set; }
            public string tj_0 { get; set; }
            public string ts_0 { get; set; }
            public string rt_0 { get; set; }
            public string sf_0 { get; set; }
            public string sv_0 { get; set; }
            public string qi_0 { get; set; }
            public string bz_0 { get; set; }
            public string db_0 { get; set; }
            public string vw_0 { get; set; }
            public string zl_0 { get; set; }
            public string wf_0 { get; set; }
            public string lw_0 { get; set; }
            public string co_0 { get; set; }
            public string ey_0 { get; set; }
            public string ge_0 { get; set; }
            public string os_0 { get; set; }
            public string ql_0 { get; set; }
            public string cq_0 { get; set; }
            public string xk_0 { get; set; }
            public string py_0 { get; set; }
            public string rv_0 { get; set; }
            public string jl_0 { get; set; }
            public string pr_0 { get; set; }
            public string pu_0 { get; set; }
            public string dk_0 { get; set; }
            public string fm_0 { get; set; }
            public string ph_0 { get; set; }
            public string sw_0 { get; set; }
            public string nr_0 { get; set; }
            public string hy_0 { get; set; }
            public string tr_0 { get; set; }
            public string pq_0 { get; set; }
            public string ff_0 { get; set; }
            public string sd_0 { get; set; }
            public string ry_0 { get; set; }
            public string le_0 { get; set; }
            public string hr_0 { get; set; }
            public string qa_0 { get; set; }
            public string wc_0 { get; set; }
            public string kw_0 { get; set; }
            public string jg_0 { get; set; }
            public string mj_0 { get; set; }
            public string eu_0 { get; set; }
            public string ll_0 { get; set; }
            public string ed_0 { get; set; }
            public string pp_0 { get; set; }
            public string th_0 { get; set; }
            public string xr_0 { get; set; }
            public string iz_0 { get; set; }
            public string tk_0 { get; set; }
            public string rx_0 { get; set; }
            public string ki_0 { get; set; }
            public string my_0 { get; set; }
            public string zm_0 { get; set; }
            public string tq_0 { get; set; }
            public string au_0 { get; set; }
            public string ei_0 { get; set; }
            public string rp_0 { get; set; }
            public string pa_0 { get; set; }
            public string fs_0 { get; set; }
            public string ul_0 { get; set; }
            public string cf_0 { get; set; }
            public string bt_0 { get; set; }
            public string ud_0 { get; set; }
            public string qu_0 { get; set; }
            public string un_0 { get; set; }
            public string rm_0 { get; set; }
            public string uo_0 { get; set; }
            public string ti_0 { get; set; }
            public string nk_0 { get; set; }
            public string jm_0 { get; set; }
            public string lp_0 { get; set; }
            public string si_0 { get; set; }
            public string fj_0 { get; set; }
            public string pt_0 { get; set; }
            public string qc_0 { get; set; }
            public string yo_0 { get; set; }
            public string ve_0 { get; set; }
            public string qh_0 { get; set; }
            public string iu_0 { get; set; }
            public string ib_0 { get; set; }
            public string zv_0 { get; set; }
            public string jb_0 { get; set; }
            public string vn_0 { get; set; }
            public string wn_0 { get; set; }
            public string bj_0 { get; set; }
            public string st_0 { get; set; }
            public string ev_0 { get; set; }
            public string qn_0 { get; set; }
            public string cd_0 { get; set; }
            public string vo_0 { get; set; }
            public string il_0 { get; set; }
            public string dx_0 { get; set; }
            public string el_0 { get; set; }
            public string dn_0 { get; set; }
            public string lk_0 { get; set; }
            public string vc_0 { get; set; }
            public string wj_0 { get; set; }
            public string wk_0 { get; set; }
            public string jj_0 { get; set; }
            public string an_0 { get; set; }
            public string jr_0 { get; set; }
            public string nb_0 { get; set; }
            public string gv_0 { get; set; }
            public string dw_0 { get; set; }
            public string gj_0 { get; set; }
            public string hc_0 { get; set; }
            public string uf_0 { get; set; }
            public string kn_0 { get; set; }
            public string qd_0 { get; set; }
            public string hn_0 { get; set; }
            public string zf_0 { get; set; }
            public string gi_0 { get; set; }
            public string uc_0 { get; set; }
            public string mn_0 { get; set; }
            public string ak_0 { get; set; }
            public string cp_0 { get; set; }
            public string qo_0 { get; set; }
            public string wx_0 { get; set; }
            public string et_0 { get; set; }
            public string px_0 { get; set; }
            public string jh_0 { get; set; }
            public string lb_0 { get; set; }
            public string md_0 { get; set; }
            public string lt_0 { get; set; }
            public string sk_0 { get; set; }
            public string oh_0 { get; set; }
            public string km_0 { get; set; }
            public string af_0 { get; set; }
            public string tt_0 { get; set; }
            public string jf_0 { get; set; }
            public string az_0 { get; set; }
            public string yn_0 { get; set; }
            public string wl_0 { get; set; }
            public string dl_0 { get; set; }
            public string gc_0 { get; set; }
            public string cn_0 { get; set; }
            public string ou_0 { get; set; }
            public string vp_0 { get; set; }
            public string rj_0 { get; set; }
            public string uh_0 { get; set; }
            public string es_0 { get; set; }
            public string be_0 { get; set; }
            public string aq_0 { get; set; }
            public string pd_0 { get; set; }
            public string zw_0 { get; set; }
            public string gm_0 { get; set; }
            public string fi_0 { get; set; }
            public string hg_0 { get; set; }
            public string qz_0 { get; set; }
            public string gz_0 { get; set; }
            public string jq_0 { get; set; }
            public string ue_0 { get; set; }
            public string xf_0 { get; set; }
            public string bp_0 { get; set; }
            public string vy_0 { get; set; }
            public string ea_0 { get; set; }
            public string hj_0 { get; set; }
            public string sh_0 { get; set; }
            public string vg_0 { get; set; }
            public string qf_0 { get; set; }
            public string nq_0 { get; set; }
            public string ww_0 { get; set; }
            public string ke_0 { get; set; }
            public string qj_0 { get; set; }
            public string ol_0 { get; set; }
            public string tm_0 { get; set; }
            public string ra_0 { get; set; }
            public string xj_0 { get; set; }
            public string vd_0 { get; set; }
            public string ni_0 { get; set; }
            public string mr_0 { get; set; }
            public string hx_0 { get; set; }
            public string bv_0 { get; set; }
            public string sj_0 { get; set; }
            public string td_0 { get; set; }
            public string dm_0 { get; set; }
            public string xs_0 { get; set; }
            public string kz_0 { get; set; }
            public string nu_0 { get; set; }
            public string kr_0 { get; set; }
            public string pz_0 { get; set; }
            public string hb_0 { get; set; }
            public string xe_0 { get; set; }
            public string io_0 { get; set; }
            public string ad_0 { get; set; }
            public string zg_0 { get; set; }
            public string ij_0 { get; set; }
            public string sl_0 { get; set; }
            public string wp_0 { get; set; }
            public string en_0 { get; set; }
            public string zo_0 { get; set; }
            public string vx_0 { get; set; }
            public string hl_0 { get; set; }
            public string lq_0 { get; set; }
            public string uj_0 { get; set; }
            public string ga_0 { get; set; }
            public string bo_0 { get; set; }
            public string fz_0 { get; set; }
            public string vm_0 { get; set; }
            public string ch_0 { get; set; }
            public string yp_0 { get; set; }
            public string cs_0 { get; set; }
            public string yg_0 { get; set; }
            public string lj_0 { get; set; }
            public string oz_0 { get; set; }
            public string wh_0 { get; set; }
            public string wt_0 { get; set; }
            public string og_0 { get; set; }
            public string xq_0 { get; set; }
            public string xh_0 { get; set; }
            public string kc_0 { get; set; }
            public string hk_0 { get; set; }
            public string yz_0 { get; set; }
            public string eo_0 { get; set; }
            public string ft_0 { get; set; }
            public string tf_0 { get; set; }
            public string lv_0 { get; set; }
            public string dy_0 { get; set; }
            public string lx_0 { get; set; }
            public string nn_0 { get; set; }
            public string zs_0 { get; set; }
            public string kx_0 { get; set; }
            public string ee_0 { get; set; }
            public string tp_0 { get; set; }
            public string ku_0 { get; set; }
            public string ca_0 { get; set; }
            public string va_0 { get; set; }
            public string ej_0 { get; set; }
            public string yu_0 { get; set; }
            public string np_0 { get; set; }
            public string uy_0 { get; set; }
            public string sb_0 { get; set; }
            public string zd_0 { get; set; }
            public string zn_0 { get; set; }
            public string je_0 { get; set; }
            public string gw_0 { get; set; }
            public string qk_0 { get; set; }
            public string xi_0 { get; set; }
            public string ju_0 { get; set; }
            public string dv_0 { get; set; }
            public string mk_0 { get; set; }
            public string iy_0 { get; set; }
            public string ys_0 { get; set; }
            public string ax_0 { get; set; }
            public string aw_0 { get; set; }
            public string ne_0 { get; set; }
            public string fr_0 { get; set; }
            public string mf_0 { get; set; }
            public string he_0 { get; set; }
            public string od_0 { get; set; }
            public string gu_0 { get; set; }
            public string xd_0 { get; set; }
            public string gf_0 { get; set; }
            public string yy_0 { get; set; }
            public string dg_0 { get; set; }
            public string oc_0 { get; set; }
            public string sm_0 { get; set; }
            public string aj_0 { get; set; }
            public string ta_0 { get; set; }
            public string cj_0 { get; set; }
            public string vz_0 { get; set; }
            public string yv_0 { get; set; }
            public string xy_0 { get; set; }
            public string bn_0 { get; set; }
            public string ik_0 { get; set; }
            public string rk_0 { get; set; }
            public string vj_0 { get; set; }
            public string sz_0 { get; set; }
            public string cr_0 { get; set; }
            public string oq_0 { get; set; }
            public string of_0 { get; set; }
            public string gk_0 { get; set; }
            public string bb_0 { get; set; }
            public string mh_0 { get; set; }
            public string hq_0 { get; set; }
            public string fw_0 { get; set; }
            public string cu_0 { get; set; }
            public string mi_0 { get; set; }
            public string zi_0 { get; set; }
            public string aa_0 { get; set; }
            public string rf_0 { get; set; }
            public string so_0 { get; set; }
            public string zq_0 { get; set; }
            public string xt_0 { get; set; }
            public string ln_0 { get; set; }
            public string us_0 { get; set; }
            public string kg_0 { get; set; }
            public string gh_0 { get; set; }
            public string lh_0 { get; set; }
            public string wo_0 { get; set; }
            public string rg_0 { get; set; }
            public string cz_0 { get; set; }
            public string tu_0 { get; set; }
            public string ih_0 { get; set; }
            public string rh_0 { get; set; }
            public string xb_0 { get; set; }
            public string fc_0 { get; set; }
            public string hi_0 { get; set; }
            public string fl_0 { get; set; }
            public string oy_0 { get; set; }
            public string jx_0 { get; set; }
            public string rc_0 { get; set; }
            public string eg_0 { get; set; }
            public string ba_0 { get; set; }
            public string oe_0 { get; set; }
            public string gs_0 { get; set; }
            public string ml_0 { get; set; }
            public string mq_0 { get; set; }
            public string jt_0 { get; set; }
            public string sp_0 { get; set; }
            public string ot_0 { get; set; }
        }//Количество свободных номеров
    }
}
